project:
  type: book
  output-dir: _book
title-block-banner: assets/branding/images/cover-image.jpg

book:
  title: "Bridgeframe"
  subtitle: "Bridging Business Analysis and Public Health"
  author: 
  - name: "Andr√© van Zyl"
    id: avz
    orcid: 0000-0001-6872-5276
    url: https://www.linkedin.com/in/andre-van-zyl/
    affiliation: 
      - name: Intersect Collaborations LLC
        city: Cincinnati
        state: OH
        url: https://www.intersectcollaborations.com/
  date: last-modified
  date-format: "MMMM YYYY"
  cover-image: assets/branding/images/cover-image.jpg
  chapters:
    - index.qmd
    - preface.qmd
    - part: "Foundations"
      chapters:
        - chapters/01-introduction.qmd
        - chapters/02-case-study.qmd
        - chapters/03-terminology.qmd
    - part: "The Analysis Process"
      chapters:
        - chapters/04-planning.qmd
        - chapters/05-elicitation.qmd
        - chapters/06-requirements.qmd
        - chapters/07-design.qmd
        - chapters/08-implementation.qmd
        - chapters/09-evaluation.qmd
    - part: "Putting It Into Practice"
      chapters:
        - chapters/10-tools.qmd
        - chapters/11-implementation-science.qmd
        - chapters/12-process-optimization.qmd
        - chapters/13-automation-intake.qmd
    - part: "Appendices"
      chapters:
        - chapters/A-templates.qmd
        - chapters/B-development-tools.qmd
        - chapters/D-workforce-development.qmd
        - chapters/E-career-navigation.qmd
        - chapters/C-glossary.qmd
    - references.qmd
  
  downloads:
    - docx
  
  sidebar:
    search: true
  
  repo-url: https://github.com/andre-inter-collab-llc/Bridgeframe-Toolkit
  repo-actions: [issue]

bibliography: assets/references/Bridgeframe.bib
csl: assets/references/vancouver-superscript.csl

execute:
  freeze: auto

format:
  html:
    theme:
      - brand
      - assets/styles/custom.scss
    toc: true
    toc-depth: 5
    number-sections: true
    code-fold: true
    code-tools: true
  
  docx:
    reference-doc: assets/branding/templates/IntersectCollab-reference-doc.docx
    toc: true
    number-sections: false
    toc-depth: 2
